/* LAMF Ad Content Tool — content extracted & authored from the Shriram Credit workbook.
   pin: headlines use 1|2|3 (RSA position), null = rotates. descriptions use 1|2, null = rotates. */
(function () {
  const HL_LIMIT = 30, DESC_LIMIT = 90, PATH_LIMIT = 15;

  // helper to build headline/description objects
  const h = (text, pin = null) => ({ text, pin });
  const d = (text, pin = null) => ({ text, pin });

  const campaigns = [
    {
      id: "personal-loan",
      name: "Personal Loan Intercept",
      adGroup: "Personal Loan",
      account: "Shriram Credit — LAMF Search",
      theme: "Personal Loan Alternatives",
      audience: "High-intent personal-loan searchers",
      finalUrl: "https://www.shriramcredit.com/lamf/apply",
      path1: "lamf",
      path2: "apply-now",
      status: "Review",
      priority: "High",
      headlines: [
        h("Looking For A Personal Loan?"),
        h("LAMF @ 10.5%* p.a.", 2),
        h("Smarter Than A Personal Loan"),
        h("MF Units Stay. Cash Arrives."),
        h("Don't Sell MF. Pledge It."),
        h("100% Digital Process"),
        h("SEBI & RBI Regulated NBFC"),
        h("Get Funds Up To ₹2 Cr*"),
        h("Stay Invested. Access Funds."),
        h("Apply Now. Get Funds Fast.", 3),
        h("Check Eligibility Now"),
        h("Why Pay 18%+ On A Loan?"),
        h("40+ Years Of Trusted Legacy"),
        h("No Asset Loss. Just Liquidity"),
        h("Get Cash. Stay Invested."),
      ],
      descriptions: [
        d("Skip the personal loan. Pledge your MF units & get funds at 10.5%* p.a. Stay invested.", 1),
        d("MF units lien-marked, not sold. Your portfolio grows while you access the cash you need."),
        d("100% digital. Fast approval. Apply in minutes & unlock your credit line. No branch visits."),
        d("Shriram Credit — SEBI & RBI regulated NBFC. 40+ years of legacy. Check eligibility today.", 2),
      ],
    },
    {
      id: "instant-cash",
      name: "Instant Cash Intercept",
      adGroup: "Instant / Quick Cash",
      account: "Shriram Credit — LAMF Search",
      theme: "Instant Cash",
      audience: "Users searching instant / quick cash",
      finalUrl: "https://www.shriramcredit.com/lamf/instant",
      path1: "lamf",
      path2: "instant-cash",
      status: "In Progress",
      priority: "High",
      headlines: [
        h("Need Instant Cash Today?"),
        h("LAMF @ 10.5%* p.a.", 2),
        h("Cash In Minutes, Not Days"),
        h("Pledge MF. Get Funds Fast."),
        h("Don't Sell. Don't Wait."),
        h("100% Digital. Instant Setup."),
        h("SEBI & RBI Regulated NBFC"),
        h("Funds Up To ₹2 Cr*"),
        h("Your MF Is Your Cash Reserve"),
        h("Apply Now. Get Funds Fast.", 3),
        h("Check Eligibility In Minutes"),
        h("Quick Cash Without Selling MF"),
        h("Same-Day Digital Approval"),
        h("Instant Liquidity, Zero Loss"),
        h("Get Cash. Stay Invested."),
      ],
      descriptions: [
        d("Need cash fast? Pledge your MF units & unlock funds at 10.5%* p.a. Instantly. Stay invested.", 1),
        d("MF units lien-marked, not sold. Access instant liquidity while your portfolio keeps growing."),
        d("100% digital. Same-day approval. Apply in minutes & unlock your credit line. No branch visits."),
        d("Shriram Credit — SEBI & RBI regulated NBFC. 40+ years of legacy. Check eligibility today.", 2),
      ],
    },
    {
      id: "emergency-cash",
      name: "Emergency Cash Intercept",
      adGroup: "Emergency Cash",
      account: "Shriram Credit — LAMF Search",
      theme: "Emergency Cash",
      audience: "Medical / urgent expense searchers",
      finalUrl: "https://www.shriramcredit.com/lamf/emergency",
      path1: "lamf",
      path2: "emergency",
      status: "Not Started",
      priority: "High",
      headlines: [
        h("Facing An Emergency Expense?"),
        h("LAMF @ 10.5%* p.a.", 2),
        h("Your MF Is An Emergency Fund"),
        h("Pledge MF. Cover The Crisis."),
        h("Don't Break Your Portfolio"),
        h("100% Digital Emergency Loan"),
        h("SEBI & RBI Regulated NBFC"),
        h("Funds Up To ₹2 Cr*"),
        h("Medical Needs? Pledge MF."),
        h("Apply Now. Get Funds Fast.", 3),
        h("Check Eligibility Now"),
        h("Cash For Any Emergency"),
        h("40+ Years Of Trusted Legacy"),
        h("Liquidity When You Need It"),
        h("Get Cash. Stay Invested."),
      ],
      descriptions: [
        d("Emergency? Pledge your MF units & get funds at 10.5%* p.a. Fast. Keep your investments intact.", 1),
        d("Your MF portfolio is your emergency fund. Lien-mark units, get cash, investments stay invested."),
        d("100% digital. Fast approval for urgent needs. Apply in minutes. No branch visits, no delays."),
        d("Shriram Credit — SEBI & RBI regulated NBFC. 40+ years of legacy. Check eligibility today.", 2),
      ],
    },
    {
      id: "urgent-money",
      name: "Urgent Money Intercept",
      adGroup: "Urgent Money Need",
      account: "Shriram Credit — LAMF Search",
      theme: "Urgent Money",
      audience: "Urgent money / fast funds searchers",
      finalUrl: "https://www.shriramcredit.com/lamf/urgent",
      path1: "lamf",
      path2: "urgent-funds",
      status: "Not Started",
      priority: "Medium",
      headlines: [
        h("Need Money Urgently?"),
        h("LAMF @ 10.5%* p.a.", 2),
        h("Urgent Funds Without Selling MF"),
        h("Pledge MF. Get Money Now."),
        h("Skip The 18%+ Personal Loan"),
        h("100% Digital. Fast Disbursal."),
        h("SEBI & RBI Regulated NBFC"),
        h("Funds Up To ₹2 Cr*"),
        h("Fast Money, No Asset Loss"),
        h("Apply Now. Get Funds Fast.", 3),
        h("Check Eligibility Now"),
        h("Why Sell When You Can Pledge?"),
        h("40+ Years Of Trusted Legacy"),
        h("Urgent Liquidity, Intact Wealth"),
        h("Get Cash. Stay Invested."),
      ],
      descriptions: [
        d("Need money urgently? Pledge MF units & get funds at 10.5%* p.a. Fast. Stay fully invested.", 1),
        d("MF units lien-marked, not sold. Get urgent funds while your portfolio continues to grow."),
        d("100% digital. Fast disbursal. Apply in minutes & unlock your credit line. No branch visits."),
        d("Shriram Credit — SEBI & RBI regulated NBFC. 40+ years of legacy. Check eligibility today.", 2),
      ],
    },
    {
      id: "low-interest",
      name: "Low-Interest Loan Intercept",
      adGroup: "Low-Interest Loan",
      account: "Shriram Credit — LAMF Search",
      theme: "Low-Rate Loan",
      audience: "Rate-sensitive loan comparison shoppers",
      finalUrl: "https://www.shriramcredit.com/lamf/rates",
      path1: "lamf",
      path2: "low-rate",
      status: "In Progress",
      priority: "High",
      headlines: [
        h("Want A Low-Interest Loan?"),
        h("LAMF @ 10.5%* p.a.", 2),
        h("Half The Cost Of A Loan"),
        h("Pay Only On What You Use"),
        h("Why Pay 18%+ On A Loan?"),
        h("100% Digital Process"),
        h("SEBI & RBI Regulated NBFC"),
        h("Funds Up To ₹2 Cr*"),
        h("Lower Rate. Stay Invested."),
        h("Apply Now. Get Funds Fast.", 3),
        h("Check Your Rate In Minutes"),
        h("The Math Is Clear. Switch."),
        h("40+ Years Of Trusted Legacy"),
        h("Smart Borrowing Starts Here"),
        h("Get Cash. Stay Invested."),
      ],
      descriptions: [
        d("Personal loans charge 18-24%. LAMF starts at 10.5%* p.a. Pay only on the amount you use.", 1),
        d("MF units lien-marked, not sold. Lower your borrowing cost while your portfolio keeps growing."),
        d("100% digital. Fast approval. Apply in minutes & unlock your credit line. No branch visits."),
        d("Shriram Credit — SEBI & RBI regulated NBFC. 40+ years of legacy. Check eligibility today.", 2),
      ],
    },
    {
      id: "wealth-preservation",
      name: "Wealth Preservation",
      adGroup: "Investor Mindset",
      account: "Shriram Credit — LAMF Search",
      theme: "Wealth / Investor",
      audience: "Long-term MF investors avoiding redemption",
      finalUrl: "https://www.shriramcredit.com/lamf/investors",
      path1: "lamf",
      path2: "investors",
      status: "Not Started",
      priority: "Medium",
      headlines: [
        h("Don't Redeem. Pledge Instead."),
        h("LAMF @ 10.5%* p.a.", 2),
        h("Keep Your Portfolio Compounding"),
        h("No Redemption. No Tax Event."),
        h("Smart Investors Don't Sell"),
        h("100% Digital Process"),
        h("SEBI & RBI Regulated NBFC"),
        h("Funds Up To ₹2 Cr*"),
        h("Let Your MF Work For You"),
        h("Unlock Liquidity Today.", 3),
        h("Check Eligibility Now"),
        h("Liquidity Without Disruption"),
        h("40+ Years Of Trusted Legacy"),
        h("Preserve Wealth. Access Cash."),
        h("Stay Invested. Access Funds."),
      ],
      descriptions: [
        d("Your wealth shouldn't stop working while you access liquidity. LAMF keeps both intact @ 10.5%* p.a.", 1),
        d("No redemption, no capital gains tax event. Pledge MF units & keep your portfolio compounding."),
        d("100% digital. Fast approval. Apply in minutes & unlock your credit line. No branch visits."),
        d("Shriram Credit — SEBI & RBI regulated NBFC. 40+ years of legacy. Check eligibility today.", 2),
      ],
    },
  ];

  window.LAMF_DATA = {
    limits: { headline: HL_LIMIT, description: DESC_LIMIT, path: PATH_LIMIT, sitelinkTitle: 25, sitelinkDesc: 35, callout: 25 },
    brand: {
      product: "Loan Against Mutual Funds (LAMF)",
      rate: "10.5%* p.a.",
      maxLoan: "Up to ₹2 Cr*",
      regulator: "SEBI & RBI",
      founded: "1974 — 40+ years legacy",
      collateral: "MF units lien-marked, NOT sold",
      coreUsp: "Stay invested. Access funds.",
    },
    statuses: ["Not Started", "In Progress", "Review", "Approved", "Live"],
    campaigns,
    pinningGuide: [
      { slot: "HL Pin 1", rule: "Intent mirror — echo the searcher's query", pinned: false },
      { slot: "HL Pin 2 ★", rule: "“LAMF @ 10.5%* p.a.” — always pinned (Rule 8)", pinned: true },
      { slot: "HL Pin 3", rule: "Call to action — “Apply Now. Get Funds Fast.”", pinned: true },
      { slot: "Desc Pin 1", rule: "Rate reframe vs. a personal loan", pinned: true },
      { slot: "Desc Pin 2", rule: "Trust signal + CTA", pinned: true },
    ],
    sitelinks: [
      ["Apply for LAMF", "Check your eligibility in minutes", "100% digital — apply from phone"],
      ["Calculate Loan Value", "Know your LAMF loan limit now", "Enter MF portfolio value to check"],
      ["Why LAMF?", "Better rates than personal loans", "MF units lien-marked, not sold"],
      ["About Shriram Credit", "SEBI & RBI regulated NBFC", "40+ years of trusted legacy"],
      ["LAMF Interest Rates", "10.5%* p.a. — interest on use", "Pay only for what you withdraw"],
      ["Pledge Your MF Now", "Simple lien-mark process", "No redemption — portfolio grows"],
      ["LAMF for Medical Needs", "Emergency fund without selling", "Fast digital approval process"],
      ["LAMF for Education", "Fund education, stay invested", "No capital gains tax event"],
    ],
    callouts: [
      "LAMF @ 10.5%* p.a.", "100% Digital Process", "SEBI & RBI Regulated", "40+ Years Legacy",
      "MF Units Not Sold", "Quick Approval", "Pay Only On Usage", "No Capital Gains Tax*",
      "No Foreclosure Charges*", "Zero Processing Fees*", "Fast Disbursal", "Up To ₹2 Cr*",
      "Stay Invested", "Lien-Mark, Not Redeem", "Trusted NBFC", "Same-Day Approval",
      "Wealth Continues", "No Branch Visit", "Secure Digital Process", "Flexible Repayment",
    ],
    snippets: [
      { header: "Services", values: ["LAMF", "Credit Line", "Loan Pledge", "Quick Approval", "Digital Process"] },
      { header: "Features", values: ["Low Interest Rate", "Stay Invested", "MF Units Safe", "No Redemption", "100% Digital", "Fast Disbursal", "SEBI Regulated"] },
      { header: "Benefits", values: ["10.5%* p.a. Rate", "No Tax Event*", "No Foreclosure*", "Portfolio Safe", "Funds Fast"] },
    ],
    images: [
      ["LAMF Rate Hero", "10.5%* p.a. rate graphic — gold on navy", "1200×628"],
      ["Stay Invested Visual", "MF portfolio graph + cash visual", "1200×628"],
      ["Wedding Scenario", "Happy wedding couple — with LAMF overlay", "1200×628"],
      ["Education Scenario", "Student with laptop — education funding", "1200×628"],
      ["Square — Rate", "10.5%* rate badge — square format", "1200×1200"],
    ],
    promotions: [
      ["None / Ongoing", "Rates From 10.5%* p.a.", "", "", 22],
      ["Dussehra", "Rate Special Offer", "01-Oct", "15-Oct", 18],
      ["Financial Year End", "Check Eligibility Now", "01-Mar", "31-Mar", 21],
    ],
  };
})();
